# Generated by Django 3.2 on 2021-04-26 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('done', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
